name: Run build test

on:
  push:
    branches:
      - yotube
  pull_request:
    branches:
      - yotube

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Eslint check
        run: npm run lint

      - name: Test Build
        run: npm run build-test
